# for loop pehle non iterable ko iterable banata hai
s='samarthsinghadhikari03@gmail.com'
s1=iter(s)
#print(s1)# isse object ka address aa jayega
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
print(next(s1))
# so on 
